# Generated by Django 6.0.5 on 2026-05-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_level_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonnummer')),
                ('status', models.CharField(choices=[('Pending', 'Ausstehend'), ('Confirmed', 'Bestätigt'), ('Waitlisted', 'Warteliste'), ('Cancelled', 'Storniert')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registriert am')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.course', verbose_name='Kurs')),
            ],
        ),
    ]
